# Generated by Django 5.2.6 on 2025-09-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_post_categorias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha']},
        ),
    ]
