# Generated by Django 5.2.6 on 2025-09-17 21:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20250917_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatars/default.png', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
